name: 'dogs4heyra'
version: '1.0.0'
config-version: 2

profile: 'dogs4heyra'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dogs4heyra:
    bronze:
      +schema: dog_breeds_bronze
      +materialized: view
    silver:
      +schema: dog_breeds_silver
      +materialized: view
    gold:
      +schema: dog_breeds_gold
      +materialized: table
